SHELL=/bin/bash -e

help:
	@echo - make install -------- Install dependencies
	@echo - make noise ---------- Send notification

.PHONY: install
install:
	@npm install

.PHONY: noise
noise:
	@node index.js
